/*
 * RRG: statistical reporting system.
 *  
 * This file is part of the RRG project (https://github.com/ipeszek/RRG) which is released under GNU General Public License v3.0.
 * You can use RRG source code for statistical reporting but not to create for-profit selleable product. 
 * See the LICENSE file in the root directory or go to https://www.gnu.org/licenses/gpl-3.0.en.html for full license details.
 */

%macro __transposes(
  dsin=, 
  varby=,
  groupby=,
  trtvar=,
  overall=0)/store;

%local dsin  varby groupby trtvar overall;
%local i grpstuff ngrp ngrpw tmp tmp2 lastgrplab;
%let ngrp=0;
%let groupby = %lowcase(&groupby);
%let ngrpw=0;
%if %length(&groupby) %then %let ngrpw = %sysfunc(countw(&groupby, %str( )));
%do i=1 %to &ngrpw;
  %let tmp = %scan(&groupby, &i, %str( ));
  %if %index(&tmp, __order_)ne 1 %then %do;
     %let ngrp=%eval(&ngrp+1);
     %let grpstuff=&grpstuff __grplabel_&tmp;
     %let lastgrplab = __grplabel_&tmp;
  %end;
%end;

%local  ntrt;
%if %length(&trtvar)=0 %then %let ntrt=1;
%else %let ntrt = %sysfunc(countw(&trtvar, %str( )));

%* IP 2009-10-06;
  
%* determine skiplines for grouping variables;
proc sql noprint;
  %local grpvar tmp2 numog someskips lastgrpskip;
  %let tmp2=0;
  %let numog=0;
  %let someskips=0;
  %do i=1 %to &ngrpw;
    %let grpvar = %upcase(%scan(&groupby, &i, %str( )));
    %let tmp=;
    select upcase(skipline) into:tmp separated by ' ' from __varinfo
        where upcase(name)="&grpvar";
    %if %length(&tmp) %then %do;
      %let tmp2 = %eval(&tmp2+1);
      %let numog =%eval(&numog+1);
      %local skip&tmp2 grp&tmp2;
      %let skip&tmp2 = &tmp;
      %let grp&tmp2=&grpvar;
      %if "&tmp"="Y" %then %do;
        %let someskips=1;
        %let lastgrpskip=&grpvar;
      %end;  
    %end;  
  %end;
quit;  

 

*** MAKE DATASET LONG AND SKINNY - RECREATE __TRTID ;


data rrgpgmtmp;
length record $ 2000;
keep record;
record = " ";
%if &overall>0 %then %do;
    record = '%local i regtrt  ovtrt colovtrt;'; output;
    record = " ";output;
    record = " ";output;
    record =  "proc sql noprint;";output;
    record =  "  select distinct __trtid into:regtrt separated by ' '";output;
    record =  "    from __poph(where=(__overall=0));";output;
    record =  "  select distinct __trtid into:ovtrt separated by ' '";output;
    record =  "    from __poph(where=(__overall=1));";output;
    record =  "  select distinct cats('__col_', __trtid) into:colovtrt ";output;
    record =  "    separated by ' ' from __poph(where=(__overall=1));";output;
    record =  "quit;";output;
    record = " ";output;
    record = " ";output;
    record =  "data __all2o;";output;
    record =  "set __all;";output;
    record =  "if 0 then __varbylab='';";output;
    record =  "keep &varby  __varbylab __tby __align";output;
    record =  "   &groupby ";output;
    record =  "   &grpstuff ";output;
    record =  "    __grpid __grptype ";output;
    record =  '   &colovtrt;';output;
    record =  "run;";output;
%end;
record = " ";output;
record = " ";output;
record =  "data __all2;";output;
record =  "set &dsin  (where = (__vtype in ('CAT','COND','CONT','OV','CATS')";output;
record =  '   and __grpid=ceil(__grpid)));';output;
record =  "if 0 then __varbylab='';";output;
record =  "length __colx __col0 $ 2000;";output;
record =  'array cols{*} __col_1-__col_&maxtrt;';output;
record =  'array cnts{*} __cnt_1-__cnt_&maxtrt;';output;
record =  'array pcts{*} __pct_1-__pct_&maxtrt;';output;
record =  'array cevs{*} __colevt_1-__colevt_&maxtrt;';output;
record =  '  __col0=__col_0;';output;
record =  '%do i=1 %to &maxtrt;';output;
record =  '__trtid=&i;';output;
record =  '__colx = cats(__col_&i);';output;
record =  '__cnt = __cnt_&i;';output;
record =  '__pct = __pct_&i;';output;
record =  '__colevt = __colevt_&i;';output;
record =  '__nalign = scan(__align, &i+1, ' "' ');";output;
%if &overall>0 and %length(&trtvar) %then %do;
    record =  ' if __trtid in (&regtrt) then output;';output;
%end;
%else %do;
    record =  ' output;';output;
%end;
record =  '%end;';output;
record =  "drop __col_: __pct_: __cnt_: __colevt_:;";output;
record =  "run;";output;
record = " ";output;
record = " ";output;
record =  '***************************************************************;';output;
record =  '*** GET ALL COMBINATIONS OF __TRTID AND ALL STATS VARIABLES ;';output;
record =  '*** THAT ARE TO BE PLACED IN COLUMNS;';output;
record =  '***************************************************************;';output;
record = " ";output;
record = " ";output;
record =  "proc sort data=__all2 ";output;
record =  "    (where = (__vtype in ('CAT','COND','CONT','OV','CATS')))";output;
record =  '  nodupkey out = __all3';output;
record =  " (keep=__blockid __order __vtype __col0 __varlabel __keepn ) ;";output;
record =  'by __blockid __order __col0;';output;
record =  'run;';output;
record = " ";output;
record =  'proc sort data=__all2 nodupkey out = __all4(keep=__trtid) ;';output;
record =  'by __trtid;';output;
record =  'run;';
record = " ";output;
record =  'proc sql noprint nowarn;';output;
record =  'create table __all5 as select * from';output;
record =  '__all3 cross join __all4;';output;
record =  'quit;';output;
record = " ";output;
record = " ";output;
record =  'proc sort data=__all5;';output;
record =  'by __trtid __blockid __order __vtype __col0;';output;
record =  'run;';output;
record = " ";output;
record =  '*** CREATE NEW __NTRTID (COLUMN INDICATOR);';output;
record = " ";output;
record =  'data __all5;';output;
record =  'set __all5 end=eof;';output;
record =  'by __trtid  __blockid __order  __vtype __col0;';output;
record =  '__ntrtid=_n_;';output;
record =  "if eof then call symput('maxtrt', cats(__ntrtid));";output;
record =  'run;';output;
record = " ";output;
record = " ";output;
record = " ";output;
record =  '*** MERGE __NTRTID INTO __ALL2 DATASET;';output;
record = " ";output;
record =  'proc sort data=__all2;';output;
record =  'by __trtid __blockid __order __vtype __col0;';output;
record =  'run;';output;
record = " ";output;
record =  'data __all6;';output;
record =  'merge __all2 __all5(in=__a);';output;
record =  'by __trtid __blockid __order __vtype __col0;';output;
record =  'if __a;';output;
record =  'run;';output;
record = " ";output;
record =  'proc sort data=__all6 out=__all6a (keep=__blockid __vtype )';output;
record =  'nodupkey;';output;
record =  'by __blockid __vtype ;';output;
record =  'run;';output;
record = " ";output;
record =  'proc sort data=__all6 out=__all6b (keep=__blockid __vtype __ntrtid)';output;
record =  '  nodupkey;';output;
record =  'by __blockid __ntrtid;';output;
record =  'run;';output;
record = " ";output;
record =  'data __all6c;';output;
record =  'merge __all6a __all6b;';output;
record =  'by __blockid __vtype;';output;
record =  'run;';output;
record = " ";output;
record =  'proc transpose data=__all6c out=__all7b prefix=__vt_;';output;
record =  'var __vtype;';output;
record =  'id __ntrtid;';output;
record =  'run;';output;
record = " ";output;
record =  'proc sort data=__all6;';output;
record =  "by &varby  __varbylab __tby ";output;
record =  "  &groupby &grpstuff __grpid  ";output;
record =  '  __grptype __indentlev ;';output;
record =  'run;';output;
record = " ";output;
record =  'proc transpose data=__all6 out=__all7 prefix=__col_;';output;
record =  'var __colx;';output;
record =  " by  &varby  __varbylab __tby ";output;
record =  "   &groupby &grpstuff  __grpid  ";output;
record =  '  __grptype __indentlev ;';output;
record =  'id __ntrtid;';output;
record =  'run;';output;
record = " ";output;
record =  'proc transpose data=__all6 out=__all7c prefix=__colevt_;';output;
record =  'var __colevt;';output;
record =  " by  &varby  __varbylab __tby ";output;
record =  "   &groupby &grpstuff  __grpid  ";output;
record =  '  __grptype __indentlev ;';output;
record =  'id __ntrtid;';output;
record =  'run;';output;
record = " ";output;
record =  'proc transpose data=__all6 out=__all7a prefix=__al_;';output;
record =  'var __nalign;';output;
record =  " by  &varby  __varbylab __tby ";output;
record =  "  &groupby &grpstuff __grpid  ";output;
record =  '  __grptype __indentlev ;';output;
record =  'id __ntrtid;';output;
record =  'run;';output;
record = " ";output;
record = " ";output;
record =  "data &dsin;";output;
record =  'merge  __all7 __all7a __all7c;';output;
record =  "by &varby  __varbylab __tby ";output;
record =  "  &groupby &grpstuff __grpid  ";output;
record =  '  __grptype __indentlev ;';output;
record =  'run;';output;
record = " ";output;
record =  "data &dsin;";output;
record =  "set &dsin;";output;
record =  'length __align $ 2000;';output;
record =  'if _n_=1 then set __all7b;';output;
record =  'array cols{*} __col_1-__col_&maxtrt;  ';output;
record =  'array colevt{*} __colevt_1-__colevt_&maxtrt;  ';output;
record =  'array al{*} __al_1-__al_&maxtrt;  ';output;
record =  'array vt{*} __vt_1-__vt_&maxtrt;  ';output;
record =  "__align = 'L';";output;
record =  'do __i=1 to dim(cols);';output;
%if &overall<=0 or %length(&trtvar) %then %do;
    record =  "  if vt[__i] in ('CAT', 'COND') and cols[__i]='' ";output;
    record =  "     then cols[__i]='0';";output;
    record =  "  if vt[__i] in ('CAT', 'COND') and colevt[__i]='' ";output;
    record =  "     then colevt[__i]='0';";output;
%end;
record =  "  if vt[__i] in ('CONT') and compress(cols[__i],' ,(.)')= '' ";output;
record =  "     then cols[__i]='';";output;
record =  "  if al[__i]='' then al[__i]='RD';";output;
record =  "  __align = trim(left(__align))||' '||trim(left(al[__i]));";output;
record =  'end;';output;
record =  'run;';output;
record = " ";output;
record =  "proc sort data=&dsin;";output;
record =  "  by &varby __grptype __tby ";output;
record =  "     &groupby &grpstuff __grpid ;";output;
record =  'run;';output;
record = " ";output;
%if &overall>0 and %length(&trtvar) %then %do;
    record = " ";output;
    record =  '%local i ovrename ovnemiss;';output;
    record =  '%let ovnemiss=%str(1=0);';output;
    record =  '%if %length(&colovtrt)>0 %then %do;';output;
    record =  '%do i=1 %to %sysfunc(countw(&colovtrt,%str( )));';output;
    record =  '  %let ovrename = &ovrename %scan(&colovtrt,&i, %str( )) %str(=) __col_%eval(&maxtrt+&i);';output;
    record =  '  %let ovnemiss = &ovnemiss %str(or) %scan(&colovtrt,&i, %str( )) ne ' "'';";output;
    record =  '%end;';output;
    record =  '%end;';output;
    record = " ";output;
    record =  'proc sort data=__all2o (where=(&ovnemiss));';output;
    record =  "  by &varby __grptype __tby ";output;
    record =  "     &groupby &grpstuff __grpid ;";output;
    record =  'run;';output;
%end;
record =  "data &dsin ;";output;
%if &overall>0 and %length(&trtvar) %then %do;
    record =  "  merge &dsin ";output;
    record =  '   __all2o(rename=(__align = __oldalign &ovrename));';output;
    %do i=1 %to &overall;
        %local j;
        %let j = %eval(&overall-&i+1);
        record =  "   __align = cats(__align)||' '||cats(scan(__oldalign,-&j,' '));"; output;
    %end;
%end;
%else %do;
    record =  "  set &dsin;";output;
%end;
record =  '  length __col_0 $ 2000 __vtype $ 20;';output;
record =  "  by &varby __grptype __tby ";output;
record =  "     &groupby &grpstuff __grpid;";output;
record =  '  __tmprowid=_n_;';output;
%if &ngrp>1 %then %do;
    record =  "  if last.%scan(&groupby,-2,%str( )) then __keepn=0;";output;
    record =  '  else __keepn=1;';output;
%end;
%else %do;
    record =  '  __keepn=0;';output;
%end;
record =  '  __blockid=1;';output;
record =  '  __order=1;';output;
record =  "  __col_0=' ';";output;
%if %length(&lastgrplab) %then %do;
    record =  "  __col_0=" "&lastgrplab" ";";output;
%end;
record =  '  __labelline=1;';output;
record =  "  __skipline='';";output;
record =  "  __vtype='MIXED';";output;
record =  "  __tmprid = _n_;";output;
record =  'drop __al_: __vt_:;';output;
record =  'run;';output;
record = " ";output;
%if %upcase(&aetable) ne N %then %do;
    %if &someskips=1 %then %do;
        record =  "proc sort data=&dsin;";output;
        record =  "by descending __tmprid;";output;
        record =  "run;";output;
        record = " ";output;
        record =  "data &dsin;";output;
        record =  "set &dsin end=eof;";output;
        record =  "by descending __tmprid;";output;
        record =  "__prevgrpid = lag(__grpid);";output;
        %do i=1 %to %eval(&numog-1);
            %if &&skip&i=Y %then %do;
                record =  "if  __prevgrpid = %eval(&i+1) and __prevgrpid < __grpid then __skipline='Y';";output;
                record =  "if  eof and __prevgrpid ne 999 then __skipline='Y';";output;
            %end;
        %end;
        %if &&skip&numog=Y %then %do;
            record =  "if  __grpid=999  then __skipline='Y';";output;
        %end;
        record =  "run;";output;
    %end;
%end;

%else %do;
    %if &someskips=1 %then %do;
        record =  "data &dsin;";output;
        record =  "set &dsin;";output;
        %do i=1 %to &numog;
            %if &&skip&i=Y %then %do;
                record =  "__grplabel_&&grp&i = '~-2n'||cats(__grplabel_&&grp&i);";output;
            %end;
        %end;  
        record =  "run;";output;
    %end;
%end;
record = " ";output;
record =  '*** MERGE GROUPING VARIABLE LABELS  INTO UNTRANSPOSED HEADER DATASET;';output;
record = " ";output;
record = " ";output;
record =  'proc sort data=__all5 out=__all5a(keep=__trtid __ntrtid) nodupkey;';output;
record =  'by __trtid __ntrtid;';output;
record =  'run;';output;
record = " ";output;
%if %length(&varby) %then %do;
    record =  "proc sql noprint nowarn;";output;
    record =  "  create table __all5a as select * from ( select * from __all5)";output;
    record =  "  cross join ";output;
    record =  "  (select distinct &varby from __poph);";output;
    record =  "create table __all5 as select * from __all5a;";output;
    record =  "quit;";output;
    record = " ";output;
    record =  "proc sort data=__all5a;";output;
    record =  "by &varby __trtid;";output;
    record =  "run;";output;
    record = " ";output;
%end;
record =  'data __poph0;';output;
record =  'if 0;';output;
record =  'run;';output;
record = " ";output;
%if &overall>0 and %length(&trtvar) %then %do;
    record =  'proc sort data=__poph(where=(__trtid in (&ovtrt)))';output;
    record =  '  out=__pophov;';output;
    record =  'by __trtid;';output;
    record =  'run;';output;
    record = " ";output;
    record =  'data __pophov;';output;
    record =  'set __pophov;';output;
    record =  ' by __trtid;';output;
    record =  ' retain __cnt;';output;
    record =  ' if _n_=1 then __cnt=0;';output;
    record =  ' if first.__trtid then __cnt= __cnt+1;';output;
    record =  ' __ntrtid =&maxtrt+__cnt;';output;
    record =  ' drop __cnt;';output;
    record =  'run;';output;
    record = " ";output;
    record =  '%let maxtrt = %eval(&maxtrt+'||"&overall);";output;
%end;
record = " ";output;


%local i;
%do i=1 %to &ntrt;
    %if &overall>0 and %length(&trtvar) %then %do;
        record =  "proc sort data=__poph(where=(__rowid=&i "|| ' and __trtid in (&regtrt) )) ';output;
    %end;
    %else %do;
        record =  "proc sort data=__poph(where=(__rowid=&i )) ";output;
    %end;
    record =  "    out=__poph&i;";output;
    record =  "by &varby __trtid;";output;
    record =  'run;';output;
    record = " ";output;
    record =  "data __poph&i;";output;
    record =  "merge __poph&i __all5a;";output;
    record =  "by &varby __trtid;";output;
    record =  "run;";output;
    record = " ";output;
    record =  'data __poph0;';output;
    record =  "set __poph0 __poph&i;";output;
    record =  "run;";output;
    record = " ";output;
%end; 
record =  'proc sort data=__all5;';output;
record =  'by __blockid;';output;
record =  'run;';output;
record = " ";output;
record =  'data __all5;';output;
record =  'length __col $ 2000;';output;
record =  'set __all5;';output;
record =  'by __blockid;';output;
record =  'retain __tmp;';output;
record =  'if _n_=1 then __tmp=0;';output;
record =  "__autospan='N';";output;
record =  "__rowid =  &ntrt+1;";output;
record =  "__col=cats(dequote(__varlabel));";output;
record =  "output;";output;
record =  "__rowid =  &ntrt+2;";output;
record =  "__col=cats(dequote(__col0));";output;
record =  "__autospan='N';";output;
record =  "output;";output;
record =  'run;';output;
record = " ";output;
record = " ";output;
record =  'data __poph (rename=(__ntrtid=__trtid));';output;
%if &overall>0 and %length(&trtvar) %then %do;
    record =  'set __poph0 __all5 __pophov;';output;
%end;
%else %do;
    record =  'set __poph0 __all5;';output;
%end;
record =  'drop __trtid;';output;
record =  'run;';output;
record = " ";output;
record = " ";output;
record =  'proc sort data=__poph;';output;
record =  'by __rowid __trtid ;';output;
record =  'run;';output;
record = " ";output;
record =  '*** UPDATE BREAKOKAT MACRO PARAMETER;';output;
record = " ";output;
record =  'proc sort data=__poph;';output;
record =  " by &trtvar __blockid  __order;";output;
record =  'run;';output;
record = " ";output;
record =  'data __poph;';output;
record =  '  set __poph;';output;
record =  "  by &trtvar __blockid __order;";output;
record =  '  __cb=.;';output;
record =  '  if first.__blockid then __cb=1;';output;
record =  'run;';output;
record = " ";output;
record =  "proc sort data=__poph;";output;
record =  "  by __trtid;";output;
record =  "run;";output;
record = " ";output;
record =  'proc sql noprint;';output;
record =  '  select __trtid into:breakokat separated by " " ';output;
record =  '    from __poph(where=(__cb=1));';output;
record =  'quit;';output;
record = " ";output;

run;

proc append data=rrgpgmtmp base=rrgpgm;
    run;


%mend;
